import type { Chess, Move, PieceSymbol, Square } from 'chess.js';
import type { Translations } from '../i18n/it';
import type { CandidateMove, ConversationContext, MoveIntent, ResolveResult } from './types';
import { describeMove } from './game';

/**
 * Matches a MoveIntent against the legal moves generated by chess.js.
 * The final interpretation is ALWAYS one of those legal moves:
 * 0 candidates -> error, 1 -> move, N -> clarification question.
 */

export function resolveIntent(
  intent: MoveIntent,
  chess: Chess,
  context: ConversationContext,
  t: Translations,
): ResolveResult {
  const legal = chess.moves({ verbose: true });

  switch (intent.kind) {
    case 'unknown':
      return { type: 'error', message: t.feedback.notUnderstood };

    case 'san':
      return resolveSan(intent.san, legal, t);

    case 'castle': {
      const castles = legal.filter((m) =>
        intent.side === 'k'
          ? m.isKingsideCastle()
          : intent.side === 'q'
            ? m.isQueensideCastle()
            : m.isKingsideCastle() || m.isQueensideCastle(),
      );
      if (castles.length === 0) return { type: 'error', message: t.feedback.castleImpossible };
      return finalize(castles, t);
    }

    case 'promote': {
      const promos = legal.filter((m) => m.promotion === intent.piece);
      if (promos.length === 0) return { type: 'error', message: t.feedback.illegal };
      return finalize(promos, t);
    }

    case 'move':
      return resolveMove(intent, legal, t);

    case 'capture':
      return resolveCapture(intent, legal, context, t);

    case 'clarify':
      // A clarify intent outside of a clarification is treated as a plain move guess.
      if (intent.square) return resolveMove({ kind: 'move', piece: intent.piece, to: intent.square }, legal, t);
      return { type: 'error', message: t.feedback.notUnderstood };
  }
}

function resolveSan(san: string, legal: Move[], t: Translations): ResolveResult {
  const clean = san.replace(/[+#]/g, '').toLowerCase();
  const hit = legal.find(
    (m) => m.san.replace(/[+#]/g, '').toLowerCase() === clean || m.lan.toLowerCase() === clean,
  );
  if (!hit) return { type: 'error', message: t.feedback.illegal };
  return { type: 'move', move: hit };
}

function resolveMove(
  intent: Extract<MoveIntent, { kind: 'move' }>,
  legal: Move[],
  t: Translations,
): ResolveResult {
  let candidates = legal;

  if (intent.from) candidates = candidates.filter((m) => m.from === intent.from);
  if (intent.fromFile) candidates = candidates.filter((m) => m.from[0] === intent.fromFile);
  if (intent.fromRank) candidates = candidates.filter((m) => m.from[1] === intent.fromRank);
  if (intent.to) candidates = candidates.filter((m) => m.to === intent.to);

  if (!intent.to && !intent.from) {
    return { type: 'error', message: t.feedback.notUnderstood };
  }

  let impliedPawn = false;
  if (intent.piece) {
    candidates = candidates.filter((m) => m.piece === intent.piece);
  } else if (!intent.capture && !intent.from && !intent.fromFile) {
    // "e4" means the pawn move when a pawn can go there.
    const pawnMoves = candidates.filter((m) => m.piece === 'p');
    if (pawnMoves.length > 0) {
      candidates = pawnMoves;
      impliedPawn = true;
    }
  }

  if (intent.capture) {
    const captures = candidates.filter((m) => m.captured);
    if (captures.length === 0) return { type: 'error', message: t.feedback.nothingToCapture };
    candidates = captures;
  }

  if (intent.promotion) {
    const promos = candidates.filter((m) => m.promotion === intent.promotion);
    if (promos.length > 0) candidates = promos;
  }

  if (candidates.length === 0) {
    if (intent.to) {
      if (intent.piece) return { type: 'error', message: t.feedback.noPieceCanGo(t.pieces[intent.piece], intent.to) };
      if (impliedPawn) return { type: 'error', message: t.feedback.noPawnCanGo(intent.to) };
      return { type: 'error', message: t.feedback.illegal };
    }
    return { type: 'error', message: t.feedback.illegal };
  }

  return finalize(candidates, t);
}

function resolveCapture(
  intent: Extract<MoveIntent, { kind: 'capture' }>,
  legal: Move[],
  context: ConversationContext,
  t: Translations,
): ResolveResult {
  let candidates = legal.filter((m) => m.captured);
  if (candidates.length === 0) return { type: 'error', message: t.feedback.noCapture };

  if (intent.targetSquare) candidates = candidates.filter((m) => m.to === intent.targetSquare);

  if (intent.targetPiece) {
    candidates = candidates.filter((m) => m.captured === intent.targetPiece);
    if (candidates.length === 0) {
      return { type: 'error', message: t.feedback.noCaptureOf(t.pieces[intent.targetPiece]) };
    }
  } else if (intent.pronoun) {
    // "take it": the piece the opponent just moved, when it can be captured.
    const last = context.lastOpponentMove;
    if (last) {
      const onLast = candidates.filter((m) => m.to === last.to && !m.isEnPassant());
      const enPassant = candidates.filter((m) => m.isEnPassant() && m.to[0] === last.to[0]);
      const narrowed = onLast.length ? onLast : enPassant;
      if (narrowed.length > 0) candidates = narrowed;
      // otherwise fall through: any legal capture, disambiguated below
    }
  }

  if (intent.withPiece) {
    const withPiece = candidates.filter((m) => m.piece === intent.withPiece);
    if (withPiece.length === 0) {
      return { type: 'error', message: t.feedback.noCaptureWith(t.pieces[intent.withPiece]) };
    }
    candidates = withPiece;
  }

  if (intent.promotion) {
    const promos = candidates.filter((m) => m.promotion === intent.promotion);
    if (promos.length > 0) candidates = promos;
  }

  if (candidates.length === 0) return { type: 'error', message: t.feedback.nothingToCapture };
  return finalize(candidates, t);
}

/**
 * Narrow the pending candidates with the user's answer to a clarification.
 */
export function resolveClarification(
  candidates: CandidateMove[],
  intent: MoveIntent,
  t: Translations,
): ResolveResult | null {
  let square: Square | undefined;
  let piece: PieceSymbol | undefined;
  let file: string | undefined;
  let rank: string | undefined;

  switch (intent.kind) {
    case 'clarify':
      square = intent.square;
      piece = intent.piece;
      file = intent.file;
      rank = intent.rank;
      break;
    case 'move':
      // "d2" / "quello in d2" / "cavallo" / "col cavallo"
      if (intent.from && intent.to) return null; // a full new command
      square = intent.to ?? intent.from;
      piece = intent.piece;
      file = intent.fromFile;
      break;
    case 'capture':
      if (intent.targetPiece || intent.targetSquare) return null;
      piece = intent.withPiece;
      break;
    case 'promote':
      piece = intent.piece;
      break;
    case 'san':
    case 'castle':
    case 'unknown':
      return null;
  }

  if (!square && !piece && !file && !rank) return null;

  const isPromotionChoice = candidates.every((m) => m.promotion);
  let narrowed = candidates;

  if (square) {
    const byFrom = narrowed.filter((m) => m.from === square);
    const byTo = narrowed.filter((m) => m.to === square);
    narrowed = byFrom.length ? byFrom : byTo;
  }
  if (piece) {
    if (isPromotionChoice) narrowed = narrowed.filter((m) => m.promotion === piece);
    else {
      const byPiece = narrowed.filter((m) => m.piece === piece);
      const byCaptured = narrowed.filter((m) => m.captured === piece);
      narrowed = byPiece.length ? byPiece : byCaptured;
    }
  }
  if (file) narrowed = narrowed.filter((m) => m.from[0] === file);
  if (rank) narrowed = narrowed.filter((m) => m.from[1] === rank);

  if (narrowed.length === 0) return { type: 'error', message: t.feedback.clarifyNotMatching };
  return finalize(narrowed, t);
}

function finalize(candidates: Move[], t: Translations): ResolveResult {
  if (candidates.length === 1) return { type: 'move', move: candidates[0] };

  // Same from & to, only the promotion differs.
  const sameFromTo = candidates.every((m) => m.from === candidates[0].from && m.to === candidates[0].to);
  if (sameFromTo && candidates.every((m) => m.promotion)) {
    return { type: 'ambiguous', candidates, question: t.feedback.promotionNeeded };
  }

  const pieces = new Set(candidates.map((m) => m.piece));
  const froms = [...new Set(candidates.map((m) => m.from))];
  if (pieces.size === 1 && froms.length === candidates.length) {
    const pieceName = t.pieces[candidates[0].piece];
    return {
      type: 'ambiguous',
      candidates,
      question: t.feedback.whichPiece(pieceName, joinOr(froms, t)),
    };
  }

  return {
    type: 'ambiguous',
    candidates,
    question: `${t.feedback.whichMove} ${joinOr(candidates.map((m) => describeMove(m, t)), t)}`,
  };
}

function joinOr(items: string[], t: Translations): string {
  if (items.length <= 1) return items.join('');
  return `${items.slice(0, -1).join(', ')} ${t.feedback.or} ${items[items.length - 1]}`;
}
